Resources:
  TeamsAppCalenderEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-${self:service}-teamsapp-calender-events-table
      AttributeDefinitions:
        - AttributeName: "organizationId"
          AttributeType: "S"
        - AttributeName: "eventId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "organizationId"
          KeyType: "HASH"
        - AttributeName: "eventId"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  teamsAppCalenderEventsTableName:
    Value: ${self:custom.stage}-${self:service}-teamsapp-calender-events-table
