Resources:
  TypeFormResponseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-${self:service}-typeform-response-table
      AttributeDefinitions:
        - AttributeName: "formId"
          AttributeType: "S"
        - AttributeName: "landingId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "formId"
          KeyType: "HASH"
        - AttributeName: "landingId"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 10

Outputs:
  typeFormFormResponseTableName:
    Value: ${self:custom.stage}-${self:service}-typeform-response-table
