Resources:
  TypeFormFormTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-${self:service}-typeform-form-table
      AttributeDefinitions:
        - AttributeName: "formId"
          AttributeType: "S"
        - AttributeName: "ts"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "formId"
          KeyType: "HASH"
        - AttributeName: "ts"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 3

Outputs:
  typeFormFormTableName:
    Value: ${self:custom.stage}-${self:service}-typeform-form-table
