Resources:
  TypeFormWorkspaceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-${self:service}-typeform-workspace-table
      AttributeDefinitions:
        - AttributeName: "organizationId"
          AttributeType: "S"
        - AttributeName: "ts"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "organizationId"
          KeyType: "HASH"
        - AttributeName: "ts"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  typeFormWorkspaceTableName:
    Value: ${self:custom.stage}-${self:service}-typeform-workspace-table
