Resources:
  TypeFormFormDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-${self:service}-typeform-form-data-table
      AttributeDefinitions:
        - AttributeName: "formId"
          AttributeType: "S"
        - AttributeName: "organizationId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "formId"
          KeyType: "HASH"
        - AttributeName: "organizationId"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 5

Outputs:
  typeFormFormDataTableName:
    Value: ${self:custom.stage}-${self:service}-typeform-form-data-table
