Resources:
  TypeFormFormByWorkspaceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-${self:service}-typeform-form-by-workspace-table
      AttributeDefinitions:
        - AttributeName: "organizationId"
          AttributeType: "S"
        - AttributeName: "formId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "organizationId"
          KeyType: "HASH"
        - AttributeName: "formId"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  typeFormFormByWorkspaceTable:
    Value: ${self:custom.stage}-${self:service}-typeform-form-by-workspace-table
