Resources:
  OrganizationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-${self:service}-organizations-table
      AttributeDefinitions:
        - AttributeName: "organizationId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "organizationId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  organizationTableName:
    Value: ${self:custom.stage}-${self:service}-organizations-table
